# Generated by Django 5.2.8 on 2025-11-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_date',
        ),
    ]
