# Generated by Django 5.2.8 on 2025-11-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_department_course_alter_student_department_profile'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE Myapp_department (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(100) NOT NULL,
                description TEXT
            );
            """,
            reverse_sql="DROP TABLE Myapp_department;"
        ),
        migrations.RunSQL(
            """
            ALTER TABLE Myapp_student ADD COLUMN department_id INTEGER REFERENCES Myapp_department(id) ON DELETE CASCADE;
            """,
            reverse_sql="ALTER TABLE Myapp_student DROP COLUMN department_id;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE Myapp_course (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(100) NOT NULL,
                code VARCHAR(10) NOT NULL UNIQUE,
                description TEXT
            );
            """,
            reverse_sql="DROP TABLE Myapp_course;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE Myapp_profile (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                bio TEXT,
                hobbies VARCHAR(200),
                student_id INTEGER NOT NULL UNIQUE REFERENCES Myapp_student(id) ON DELETE CASCADE
            );
            """,
            reverse_sql="DROP TABLE Myapp_profile;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE Myapp_course_students (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                course_id INTEGER NOT NULL REFERENCES Myapp_course(id) ON DELETE CASCADE,
                student_id INTEGER NOT NULL REFERENCES Myapp_student(id) ON DELETE CASCADE,
                UNIQUE(course_id, student_id)
            );
            """,
            reverse_sql="DROP TABLE Myapp_course_students;"
        ),
    ]
